### ISSUE TITLE
Environmental Variables need to be converted to integer

### ISSUE THREAD

**Issue by ghost** [jkaberg/tvhProxy#10]
tvhProxy.py:
` 'tunerCount': int(os.environ.get('TVH_TUNER_COUNT')) or 6,  # number of tuners in tvh`

**Comment by jkaberg** [comment]
It's already casted to int, just look at your quote @eatmoretv.

**Comment by ghost** [comment]
Sorry, I should have been clearer, the quote is my fix not from your code. The environmental variable, TVH_TUNER_COUNT,  is parsed to 'tunerCount' as text. Resulting in an incorrect tuner count being shown in plex. For example, TVH_TUNER_COUNT=4 becomes 1 tuner in plex.
p.s. Thanks for your code it makes Plex DVR actually usable :)

**Comment by jkaberg** [comment]
My bad! 😆 

Pushed and fix now
