### ISSUE TITLE
Error when running pip install -r requirements.txt

### ISSUE THREAD

**Issue by jteeuw** [jkaberg/tvhProxy#13]
Hi,

When i run pip install -r requirements.txt i get the foloowing eror: 

Command /home/tvh/tvhProxy/venv/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-NoDZ4t/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PrE8ib-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/tvh/tvhProxy/venv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-NoDZ4t/gevent
Storing debug log for failure in /root/.pip/pip.log

**Comment by filoor** [comment]
I Have the same error

**Comment by jkaberg** [comment]
This error is not related to tvhProxy. Check your environment.

**Comment by dougperx** [comment]
I've tried a couple fresh installs and I'm getting a similar error, failing to build wheel gevent... I'm on ubuntu 16.04... any ideas on how to verify the environment?

failing here...
Building wheels for collected packages: gevent, greenlet
  Running setup.py bdist_wheel for gevent ... /
