### ISSUE TITLE
Still - Device not found in Backend of PMS (No LiveTV)

### ISSUE THREAD

**Issue by SmoothMC** [jkaberg/tvhProxy#18]
This the output from net stat

tcp6       0      0 :::5004                 :::*                    LISTEN      19775/python

there is nothing listen under tcp with port 5004?

since the las t update PMS shows up that it found a new Tuner named tvhProxy but i can not connect to it

The weird thing is, when stopped the tvhProxy, PMS still found it.

**Comment by SmoothMC** [comment]
Update 

now PMS connect to TVH and found all Channels but ist still shows "Device not found in Backend"
so there is still not way get LiveTV

**Comment by mKeRix** [comment]
Did you end up finding a fix for this?

**Comment by rubyon** [comment]
how fix it? I have same problem
