### ISSUE TITLE
Missing license information for tvhProxy

### ISSUE THREAD

**Issue by seahawk1986** [jkaberg/tvhProxy#4]
Hello,
I have been asked to modify tvhProxy to make it usable with [VDR](http://www.tvdr.de) instead of tvheadend and I would like to publish the modified script. Which license has been chosen for this project and does it permit derivative works?

**Comment by jkaberg** [comment]
I've added license and authors https://github.com/jkaberg/tvhProxy/commit/e04d459619a97f788fdc41159db4079b697d7d5c

Good luck :-)
