### ISSUE TITLE
Python code needs updating

### ISSUE THREAD

**Issue by markrugman** [jkaberg/tvhProxy#43]
I couldn’t send a pull request so thought I’d write it here. 

Plex now sends requests as POST requests; as no methods are declared the default is GET and they are rejected.

Therefore the following needs replacing:
* @app.route('/lineup.post')
With:
* @app.route('/lineup.post', methods=[‘GET’, ‘POST’])

Don’t know if GET is still required but left it in.

It now works with TVH 4.2 and latest Plex Media Server.

**Comment by hazcod** [comment]
Created a pull request for you: https://github.com/jkaberg/tvhProxy/pull/44

**Comment by shottothedome** [comment]
This code update caused loading tvhProxy.py to fail for me when executed. Debian 8 followed the instructions
Failure message:

`$ python tvhProxy.py

  File "tvhProxy.py", line 66
SyntaxError: Non-ASCII character '\xe2' in file tvhProxy.py on line 66, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`

Reverting the post/get code line back to original allowed tvhProxy.py to load. Could this issue be reopened or do we need a new issue created? Issue is with the apostrophes used around get and post. They are not ascii characters
