### ISSUE TITLE
WSGIServer params

### ISSUE THREAD

**Issue by kevinhamon** [jkaberg/tvhProxy#6]
I have added this to the linuxserver.io docker in my own local repo. I had to change the code from an empty string to bind to address 0.0.0.0 otherwise I get an error trying to start the server. While this works for my case, I'm not sure that it would work for everyone, it would be cool if that pulled from an environment variable or command line param.

**Comment by jkaberg** [comment]
@kevinhamon fixed in https://github.com/jkaberg/tvhProxy/commit/c3e8220d1534c6bcdc4cd5ed782c7bbf83eb1bef
